MAJ-26 - Added more variants to the button component.
akhiljozph/maj-ui pull request #22
Opened 2024-08-13 13:20 UTC by akhiljozph

2024-08-13 14:31 UTC, mariyajamez approved these changes

2024-08-13 14:35 UTC, mariyajamez requested changes

2024-08-13 14:35 UTC, mariyajamez commented on src/components/maj-button/MajButton.tsx
> +        props.size === "large"
here **size** is a optional property. It is better to do a null checking before use it.otherwise there is a possibility of get a undefined error

2024-08-13 14:35 UTC, mariyajamez commented on src/components/maj-button/MajButton.tsx
>        disabled={props.disabled}
same as above comment

2024-08-13 14:43 UTC, akhiljozph commented on src/components/maj-button/MajButton.tsx
> +        props.size === "large"
Updated.

2024-08-13 14:43 UTC, akhiljozph commented on src/components/maj-button/MajButton.tsx
>        disabled={props.disabled}
Updated.

2024-08-13 17:09 UTC, mariyajamez approved these changes

2024-08-13 17:10 UTC, merged

2024-08-14 04:10 UTC, mariyajamez commented on src/components/maj-button/MajButton.tsx
>      <button
variant and disabled properties are also optional. So what happen, if the value is not given?Do we need a null check ?